//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active_Login
    {
        public int LoginID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> LoginTimestamp { get; set; }
        public Nullable<System.TimeSpan> LatestActionTimestamp { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
