//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log
    {
        public int LogID { get; set; }
        public string TableEffected { get; set; }
        public string AttrivuteEffected { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string NewRecordValue { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
