//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Refreshment_Line
    {
        public int Quantity { get; set; }
        public double UnitCost { get; set; }
        public int RefreshmentID { get; set; }
        public int RefreshBookingID { get; set; }
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public int VenueID { get; set; }
        public int BuildingID { get; set; }
        public int VenueBookingID { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Refreshment Refreshment { get; set; }
        public virtual Refreshment_Booking Refreshment_Booking { get; set; }
        public virtual User User { get; set; }
        public virtual Venue_Booking Venue_Booking { get; set; }
        public virtual Venue_Booking_Line Venue_Booking_Line { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
