//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation_Line
    {
        public string Description { get; set; }
        public int TypeID { get; set; }
        public int DonationID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual Donation Donation { get; set; }
        public virtual Project Project { get; set; }
        public virtual Donation_Type Donation_Type { get; set; }
    }
}
