//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donation()
        {
            this.Donation_Line = new HashSet<Donation_Line>();
        }
    
        public int DonationID { get; set; }
        public string QuantityAmount { get; set; }
        public System.DateTime DateDate { get; set; }
        public int QuatityTypeID { get; set; }
        public Nullable<int> DonorPID { get; set; }
        public Nullable<int> DonorOrgID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation_Line> Donation_Line { get; set; }
        public virtual Donor_Org Donor_Org { get; set; }
        public virtual Donor_Person Donor_Person { get; set; }
        public virtual Quantity_Type Quantity_Type { get; set; }
    }
}
