//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor_Org
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor_Org()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int DonorOrgID { get; set; }
        public string OrgName { get; set; }
        public string ContactNum { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<bool> Thanked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
    }
}
