//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFT_Requisition_Line
    {
        public int LineID { get; set; }
        public string Details { get; set; }
        public Nullable<int> QuantityEFT { get; set; }
        public Nullable<double> UnitPriceEFT { get; set; }
        public int RequisitionID { get; set; }
        public int SupplierID { get; set; }
    
        public virtual EFT_Requisition EFT_Requisition { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
