//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFT_Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EFT_Requisition()
        {
            this.EFT_Requisition_Line = new HashSet<EFT_Requisition_Line>();
        }
    
        public int RequisitionID { get; set; }
        public bool ApprovedProjectManger { get; set; }
        public bool ApprovedCEO { get; set; }
        public string ReceiptFile { get; set; }
        public bool VATInclusive { get; set; }
        public System.DateTime Date { get; set; }
        public int SupplierID { get; set; }
        public int ProjectID { get; set; }
        public int UserID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFT_Requisition_Line> EFT_Requisition_Line { get; set; }
    }
}
