//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Equipment_Schedule_Line = new HashSet<Equipment_Schedule_Line>();
            this.Repair_Request = new HashSet<Repair_Request>();
            this.Software_Licenses_Line = new HashSet<Software_Licenses_Line>();
        }
    
        public int EquipmentID { get; set; }
        public string ManufacturerName { get; set; }
        public string ModelNumber { get; set; }
        public System.DateTime DatePurchased { get; set; }
        public int ServiceIntervalMonths { get; set; }
        public string Status { get; set; }
        public Nullable<int> UserID { get; set; }
        public int TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Schedule_Line> Equipment_Schedule_Line { get; set; }
        public virtual Equipment_Type Equipment_Type { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair_Request> Repair_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Software_Licenses_Line> Software_Licenses_Line { get; set; }
    }
}
