//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_Booking_Line
    {
        public int BookingID { get; set; }
        public int EquipmentID { get; set; }
        public Nullable<int> PagesPrinted { get; set; }
        public System.TimeSpan TimeIn { get; set; }
        public System.TimeSpan TimeOut { get; set; }
        public int EquipmentBookingID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
    
        public virtual Equipment_Booking Equipment_Booking { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
