//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funder_Org
    {
        public int FunderOrgID { get; set; }
        public string OrgName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string BankingDetails { get; set; }
        public Nullable<bool> Thanked { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int TypeID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Funder_Type Funder_Type { get; set; }
    }
}
