//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funder_Person
    {
        public int FunderPersonID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public Nullable<int> CellNum { get; set; }
        public string PersonalEmail { get; set; }
        public string PostalAddress { get; set; }
        public string BankingDetails { get; set; }
        public Nullable<bool> Thanked { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public int TypeID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Funder_Type Funder_Type { get; set; }
    }
}
