//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petty_Cash_Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Petty_Cash_Requisition()
        {
            this.Petty_Cash_Requisition_Line = new HashSet<Petty_Cash_Requisition_Line>();
        }
    
        public int RequisitionID { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<bool> VATInclusive { get; set; }
        public System.DateTime ReqDate { get; set; }
        public int SupplierID { get; set; }
        public int ProjectID { get; set; }
        public int UserID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Petty_Cash_Requisition_Line> Petty_Cash_Requisition_Line { get; set; }
    }
}
