//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petty_Cash_Requisition_Line
    {
        public int LineID { get; set; }
        public string Details { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public int RequisitionID { get; set; }
        public int SupplierID { get; set; }
    
        public virtual Petty_Cash_Requisition Petty_Cash_Requisition { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
