//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software_Licenses_Line
    {
        public Nullable<System.DateTime> LastActivatedDate { get; set; }
        public bool Activated { get; set; }
        public int EquipmentID { get; set; }
        public int LicenceID { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Software_Licenses Software_Licenses { get; set; }
    }
}
