//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.EFT_Requisition = new HashSet<EFT_Requisition>();
            this.EFT_Requisition_Line = new HashSet<EFT_Requisition_Line>();
            this.Petty_Cash_Requisition = new HashSet<Petty_Cash_Requisition>();
            this.Petty_Cash_Requisition_Line = new HashSet<Petty_Cash_Requisition_Line>();
        }
    
        public int SupplierID { get; set; }
        public string Name { get; set; }
        public int VATNumber { get; set; }
        public string PostalAddress { get; set; }
        public string EmailAddress { get; set; }
        public string ContactNumber { get; set; }
        public string Bank { get; set; }
        public int AccountNumber { get; set; }
        public int BranchCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFT_Requisition> EFT_Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFT_Requisition_Line> EFT_Requisition_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Petty_Cash_Requisition> Petty_Cash_Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Petty_Cash_Requisition_Line> Petty_Cash_Requisition_Line { get; set; }
    }
}
