//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Active_Login = new HashSet<Active_Login>();
            this.Audit_Log = new HashSet<Audit_Log>();
            this.Booking_Refreshment_Line = new HashSet<Booking_Refreshment_Line>();
            this.EFT_Requisition = new HashSet<EFT_Requisition>();
            this.Equipments = new HashSet<Equipment>();
            this.Equipment_Booking_Line = new HashSet<Equipment_Booking_Line>();
            this.Petty_Cash_Requisition = new HashSet<Petty_Cash_Requisition>();
            this.Projects = new HashSet<Project>();
            this.Vehicle_Booking_Line = new HashSet<Vehicle_Booking_Line>();
            this.Venue_Booking_Line = new HashSet<Venue_Booking_Line>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Initials { get; set; }
        public string Password { get; set; }
        public string NationalID { get; set; }
        public string CellNum { get; set; }
        public string TelNum { get; set; }
        public string WorkNum { get; set; }
        public string PersonalEmail { get; set; }
        public string WorkEmail { get; set; }
        public Nullable<bool> ValidLicense { get; set; }
        public int JobTitleID { get; set; }
        public int AccessLevelID { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string AreaCode { get; set; }
        public string POAddress { get; set; }
        public string POCity { get; set; }
        public string POAreaCode { get; set; }
    
        public virtual Access_Level Access_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active_Login> Active_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Audit_Log> Audit_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Refreshment_Line> Booking_Refreshment_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EFT_Requisition> EFT_Requisition { get; set; }
        public virtual Employee_Title Employee_Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment_Booking_Line> Equipment_Booking_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Petty_Cash_Requisition> Petty_Cash_Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle_Booking_Line> Vehicle_Booking_Line { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venue_Booking_Line> Venue_Booking_Line { get; set; }
    }
}
