//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Booking_Line
    {
        public int VehicleID { get; set; }
        public string Reason { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> OdoEnd { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int VehicleBookingID { get; set; }
        public int IntervalID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle_Booking Vehicle_Booking { get; set; }
    }
}
