//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Schedule_Line
    {
        public int Veh_Schedule_ID { get; set; }
        public string Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Status { get; set; }
        public int VehicleID { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
