//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuData.Global
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue_Booking_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venue_Booking_Line()
        {
            this.Booking_Refreshment_Line = new HashSet<Booking_Refreshment_Line>();
        }
    
        public int BookingID { get; set; }
        public Nullable<int> NumberofPeople { get; set; }
        public System.DateTime DateBooked { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int UserID { get; set; }
        public int VenueID { get; set; }
        public int BuildingID { get; set; }
        public int VenueBookingID { get; set; }
        public int ProjectID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Refreshment_Line> Booking_Refreshment_Line { get; set; }
        public virtual Building Building { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual Venue_Booking Venue_Booking { get; set; }
    }
}
